#!/bin/bash

PPTX1=$1
PPTX2=$2
PPTX3=$3

TEMPDIR=$(mktemp -d)
PPTXDIR1=${TEMPDIR}/1
PPTXDIR2=${TEMPDIR}/2
PPTXDIR3=${TEMPDIR}/3

unzip -q -d $PPTXDIR1 $PPTX1
unzip -q -d $PPTXDIR2 $PPTX2
unzip -q -d $PPTXDIR3 $PPTX3


reformatxml() {
	if [[ $1 == *.xml* ]] && [ -n ["$(xmllint --noout $1)"] ]
	then
		xmllint --format $1 -o $1
	fi
}

for file in $(find $PPTXDIR1 -type f); do reformatxml $file; done
for file in $(find $PPTXDIR2 -type f); do reformatxml $file; done
for file in $(find $PPTXDIR3 -type f); do reformatxml $file; done

if [ "$#" -ne 2 ]; then
    meld "${TEMPDIR}/1" "${TEMPDIR}/2" "${TEMPDIR}/3"
else
	meld "${TEMPDIR}/1" "${TEMPDIR}/2" 
fi

rm -r $TEMPDIR

